services:
  weatherservice:
    container_name: weatherservice
    build:
      context: .
      dockerfile: services/WeatherService/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - weather-net

  geocodingservice:
    container_name: geocodingservice
    build:
      context: .
      dockerfile: services/GeocodingService/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - weather-net

  backendforfrontend:
    container_name: backendforfrontend
    build:
      context: .
      dockerfile: services/BackendForFrontend/Dockerfile
    ports:
      - "8085:8080"
    environment:
      - WEATHER_SERVICE_URL=http://weatherservice:8080/
      - GEOCODING_SERVICE_URL=http://geocodingservice:8080/
    depends_on:
      - weatherservice
      - geocodingservice
    networks:
      - weather-net

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Frontend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BFF_URL=http://backendforfrontend:8080
    networks:
      - weather-net


networks:
  weather-net:
    driver: bridge

