### Wetter abrufen
GET http://localhost:8081/weather?lat=49.4891&lon=8.4669
Accept: application/json

### Koordinaten für Heidelberg abrufen
GET http://localhost:8082/geocode?city=Hamburg
Accept: application/json

### Koordinaten abrufen mit DNS
GET http://geocodingservice:8080/geocode?city=Hamburg
Accept: application/json
