parameters:
  - name: displayName
    type: string
  - name: repository
    type: string
  - name: dockerfile
    type: string
  - name: buildContext
    type: string
    default: .
  - name: containerRegistry
    type: string
    default: acr-connection

steps:
  - task: Docker@2
    displayName: Build and push ${{ parameters.displayName }}
    inputs:
      command: buildAndPush
      containerRegistry: ${{ parameters.containerRegistry }}
      repository: ${{ parameters.repository }}
      dockerfile: ${{ parameters.dockerfile }}
      buildContext: ${{ parameters.buildContext }}
      tags: |
        latest
        $(Build.BuildId)
      arguments: --build-arg BUILD_CONFIGURATION=$(buildConfiguration)