parameters:
  - name: projects
    type: string
  - name: sdkVersion
    type: string
    default: 10.0.x

steps:
  - task: UseDotNet@2
    displayName: Use .NET ${{ parameters.sdkVersion }} SDK
    inputs:
      packageType: sdk
      version: ${{ parameters.sdkVersion }}

  - task: DotNetCoreCLI@2
    displayName: Restore tests
    inputs:
      command: restore
      projects: ${{ parameters.projects }}

  - task: DotNetCoreCLI@2
    displayName: Build tests
    inputs:
      command: build
      projects: ${{ parameters.projects }}
      arguments: --configuration $(buildConfiguration) --no-restore

  - task: DotNetCoreCLI@2
    displayName: Run tests
    inputs:
      command: test
      projects: ${{ parameters.projects }}
      arguments: --configuration $(buildConfiguration) --no-build --logger trx
      publishTestResults: true